services:
  playwright:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: playwright-test-container
    ports:
      - "9323:9323"
    env_file:
      - ../.env
    volumes:
      - ../reports:/app/playwright-report
      - ../test-results:/app/test-results
    shm_size: '2gb'
    command: pnpm exec playwright test
